apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nginx-test-label
  name: nginx-pod-yaml
spec:
  containers:
    - image: nginx:latest
      name: nginx
      volumeMounts:
        - mountPath: "/scratch"
          name: share-dir-scratch

    - image: busybox
      name: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 1000"]
      volumeMounts:
        - mountPath: "/scratch"
          name: share-dir-scratch

  volumes:
    - name: share-dir-scratch
      emptyDir:
        sizeLimit: 500Mi
# to connect 
#  kubectl exec -it pods/nginx-pod-yaml -c nginx -- bash
#  https://kubernetes.io/docs/reference/kubernetes-api/core/pod-v1/#Container
