apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
  name: httpd-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - image: httpd
          name: httpd
  strategy:
    ## THIS WILL UPATE 2 PODS AT A TIME, AND WILL KEEP 8 PODS RUNNING
    # type: RollingUpdate # it's a default value
    # rollingUpdate:
    #   maxUnavailable: 1  # you can set up in %, or per number of pods
    #   maxSurge: 1
    type: recreate # this will delete all pods and create new ones, so there will be downtime