apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealier_tag
  name: mealier-deployment
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealier_tag
  type: LoadBalancer
        
