apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealier_tag
  name: mealier-deployment 
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealier_tag
  template:
    metadata:
      labels:
        app: mealier_tag
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:nightly
          name: mealie
          ports:
            - containerPort: 9000 # This will expose the the local  host where kubernetes is running, to the container port 9000
      volumeMounts:
        - mountPath: /app/data
          name: mealie-data
      volumes:
        - name: mealie-data-storage
          persistentVolumeClaim:
            claimName: mealie-data-storage

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealier_tag
  name: mealier-deployment
spec:
  ports:
  - port: 8008 # Port to connect form your remote machine (local network)
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealier_tag
  type: LoadBalancer # Now you can connect to the IP of the node + :9000 port

