apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealier_tag
  name: mealier-deployment 
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealier_tag
  template:
    metadata:
      labels:
        app: mealier_tag
    spec:
      containers:
        - image: ghcr.io/mealie-recipes/mealie:nightly
          name: mealie
          ports:
            - containerPort: 9000 # This will expose the the lcoal host where kubernetes is running, to the container port 9000

