apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chrome
  name: chromium-browser-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - image: localhost:32000/chromium-browser:latest
        imagePullPolicy: IfNotPresent
        name: chromium-browser
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        ports:
        - containerPort: 7001

---
### service to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: google-chrome-service
spec:
  selector:
    app: chrome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7001
  type: NodePort
