apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chrome
  name: chromium_browser-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - image: 127.0.0.1:5000/chromium:latest
        name: chromium-browser
        ports:
        - containerPort: 7001

---
### service to expose the deployment
apiVersion: v1
kind: Service
metadata:
  name: google-chrome-service
spec:
  selector:
    app: chrome
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7001
  type: NodePort
