apiVersion: v1
kind: ConfigMap
metadata:
  name: mango-config
  labels:
    app: mango-label
data:
  mango_url: mongo-service  # will match the service name in mango-deployment.yml under metadata.name