# =================================
# API version and kind of resource
# =================================
apiVersion: apps/v1
kind: Deployment
# =================================
# Metadata (name, namespace, labels) and spec (replicas, selector, template) of the deployment
# =================================
metadata:
  namespace: default
  name: chromium-deployment
  labels:
    app: chromium
# Links deployment to Pods with the same label "chromium"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chromium
# =================================
# Template blueprint (Nodes and container lvl spec) blueprint for the deployment
# =================================
  template:
    metadata:
      labels:
        app: chromium
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: chromium-browser
          imagePullPolicy: Always
          image: localhost:32000/chromium-browser:latest
          ports:
            - containerPort: 7001    
          resources:
            limits:
              memory: "1000Mi"
              cpu: "2000m"
            requests:
              memory: "1000Mi"
              cpu: "2000m"
  